nginx:
    build: ./nginx/
    ports:
        - "80:80"
    links:
        - "php"
    volumes:
        - ./turdle:/home/turdle:ro

php:
    build: ./php/
    ports:
        - ":9000"
    links:
        - "db"
    environment:
        db_host: "db:3306"
        db_user: "root"
        db_password: "securepassword"
        db_name: "turdle"
    volumes:
        - ./turdle:/home/turdle:ro

db:
    image: mariadb
    ports:
        - ":3306"
    environment:
        MYSQL_ROOT_PASSWORD: securepassword
    volumes:
        - ./turdle_schema.sql:/docker-entrypoint-initdb.d/turdle_schema.sql
        - ./database:/var/lib/mysql
